name: CommandsEX
version: 1.00
authors: [iKeirNez, Jnorr44, kezz101]
main: com.commandsex.CommandsEX
permissions:
  cex.commandspam.bypass:
    default: op
    description: Bypass command spam limits